/**
 * Waypoint graph of open-water sea lanes. Routes between two points attach each
 * end to its nearest waypoint and follow these lanes. `route.test.ts` checks every
 * lane against a land/water mask, so an edit that cuts across land fails CI.
 */
export const SEA_NODES = {
  // western Mediterranean
  ligurian: [43.45, 7.65],
  riviera: [43.05, 6.95],
  capCorse: [43.2, 9.7],
  corsicaEast: [42.0, 9.85],
  costaSmeralda: [41.15, 9.8],
  lion: [42.4, 4.8],
  balearicN: [40.5, 2.8],
  mallorcaW: [39.5, 2.15],
  palmaBay: [39.35, 2.65],
  ibizaEast: [38.8, 1.75],
  cartagena: [37.4, -0.2],
  alboran: [36.15, -2.8],
  gibraltar: [35.95, -5.55],
  cadiz: [36.0, -6.8],
  tyrrhenianN: [41.3, 11.2],
  tyrrhenian: [39.8, 12.2],
  egadi: [38.4, 12.0],
  sicilyChannel: [37.3, 11.5],
  sicilySouth: [36.45, 13.6],
  passero: [36.3, 15.6],
  // central / eastern Mediterranean
  ionian: [37.5, 18.5],
  otranto: [40.1, 19.0],
  adriaticS: [41.8, 17.6],
  dubrovnikOff: [42.5, 17.95],
  peloponneseW: [37.0, 21.0],
  matapan: [36.0, 22.5],
  kythira: [35.95, 23.1],
  aegeanS: [36.4, 24.6],
  cycladesW: [37.3, 25.08],
  kasos: [35.5, 26.6],
  libyanSea: [34.2, 24.0],
  levant: [32.6, 29.5],
  portSaid: [31.6, 32.35],
  // Suez canal
  suezN: [31.2, 32.33],
  ismailia: [30.6, 32.32],
  bitterLakes: [30.3, 32.43],
  suezS: [29.9, 32.55],
  // Red Sea / Arabia
  gulfSuez: [29.0, 32.85],
  gulfSuezM: [28.45, 33.12],
  gulfSuezL: [28.05, 33.5],
  gulfSuezS: [27.7, 33.85],
  redSeaN: [26.0, 35.3],
  redSea: [21.5, 38.2],
  redSeaS: [16.5, 41.0],
  babElMandeb: [12.6, 43.33],
  aden: [12.2, 46.5],
  socotraN: [13.4, 52.5],
  arabianSea: [16.5, 60.0],
  rasAlHadd: [22.4, 60.3],
  gulfOman: [24.8, 58.3],
  gulfOmanN: [25.6, 56.9],
  hormuz: [26.58, 56.6],
  gulfEast: [26.2, 55.7],
  dubaiOff: [25.35, 55.0],
  // Indian Ocean / Australia / Tasman
  lakshadweep: [8.0, 70.0],
  indianOcean: [-12.0, 90.0],
  leeuwin: [-35.8, 114.5],
  bight: [-37.2, 130.0],
  tasmaniaS: [-44.3, 147.0],
  tasman: [-38.5, 160.0],
  northCape: [-33.9, 173.0],
  haurakiNorth: [-35.7, 175.3],
  hauraki: [-36.55, 175.05],
  coralSea: [-20.5, 155.0],
  cairnsOff: [-16.6, 146.4],
  // Pacific
  kermadec: [-33.0, -177.0],
  southPacific: [-22.0, -130.0],
  eastPacific: [-6.0, -88.0],
  panamaGulf: [7.6, -79.4],
  // Panama canal
  balboa: [8.85, -79.52],
  gatun: [9.15, -79.85],
  colon: [9.45, -79.92],
  // Caribbean / Bahamas / Florida
  caribbeanSW: [12.5, -78.0],
  caribbean: [15.0, -71.0],
  anegada: [18.45, -63.7],
  stBartsOff: [17.75, -62.95],
  antiguaOff: [17.0, -62.05],
  leewardAtl: [18.5, -61.0],
  puertoRicoN: [19.8, -66.0],
  caicosN: [22.6, -70.0],
  eleutheraN: [25.8, -76.5],
  nassauOff: [25.25, -77.35],
  nwProvidence: [26.1, -78.4],
  bimini: [26.0, -79.45],
  miamiOff: [25.77, -80.03],
  palmBeach: [26.8, -79.85],
  floridaE: [27.8, -79.9],
  carolina: [31.5, -79.0],
  hatteras: [34.9, -74.8],
  // Atlantic / Europe
  stVincent: [36.7, -9.5],
  madeiraN: [33.5, -19.5],
  atlantic: [26.0, -40.0],
  atlanticW: [27.0, -65.0],
  lisbon: [39.3, -9.9],
  finisterre: [43.3, -9.9],
  biscay: [46.0, -6.5],
  ushant: [48.5, -5.9],
  channel: [49.9, -3.0],
  channelE: [50.3, 0.2],
  dover: [51.0, 1.55],
  northSea: [52.7, 3.3],
  frisian: [53.85, 6.5],
  helgoland: [54.05, 8.1],
} as const satisfies Record<string, readonly [lat: number, lng: number]>;

export type SeaNodeId = keyof typeof SEA_NODES;

export const SEA_LANES: readonly (readonly [SeaNodeId, SeaNodeId])[] = [
  ['ligurian', 'riviera'], ['ligurian', 'capCorse'], ['capCorse', 'corsicaEast'], ['corsicaEast', 'costaSmeralda'],
  ['capCorse', 'tyrrhenianN'], ['corsicaEast', 'tyrrhenianN'], ['costaSmeralda', 'tyrrhenian'],
  ['tyrrhenianN', 'tyrrhenian'], ['tyrrhenian', 'egadi'], ['riviera', 'lion'], ['lion', 'balearicN'],
  ['balearicN', 'mallorcaW'], ['mallorcaW', 'palmaBay'], ['mallorcaW', 'ibizaEast'],
  ['palmaBay', 'ibizaEast'], ['ibizaEast', 'cartagena'], ['palmaBay', 'sicilyChannel'],
  ['cartagena', 'alboran'], ['alboran', 'gibraltar'], ['gibraltar', 'cadiz'], ['egadi', 'sicilyChannel'],
  ['sicilyChannel', 'sicilySouth'], ['sicilySouth', 'passero'], ['costaSmeralda', 'sicilyChannel'],
  ['passero', 'ionian'], ['ionian', 'otranto'], ['otranto', 'adriaticS'], ['adriaticS', 'dubrovnikOff'],
  ['ionian', 'peloponneseW'], ['peloponneseW', 'matapan'], ['matapan', 'kythira'], ['kythira', 'aegeanS'],
  ['aegeanS', 'cycladesW'], ['cycladesW', 'kasos'], ['aegeanS', 'kasos'], ['kasos', 'levant'],
  ['passero', 'libyanSea'], ['matapan', 'libyanSea'], ['libyanSea', 'levant'], ['levant', 'portSaid'],
  ['portSaid', 'suezN'], ['suezN', 'ismailia'], ['ismailia', 'bitterLakes'], ['bitterLakes', 'suezS'],
  ['suezS', 'gulfSuez'], ['gulfSuez', 'gulfSuezM'], ['gulfSuezM', 'gulfSuezL'], ['gulfSuezL', 'gulfSuezS'],
  ['gulfSuezS', 'redSeaN'], ['redSeaN', 'redSea'], ['redSea', 'redSeaS'], ['redSeaS', 'babElMandeb'],
  ['babElMandeb', 'aden'], ['aden', 'socotraN'], ['socotraN', 'arabianSea'], ['arabianSea', 'rasAlHadd'],
  ['rasAlHadd', 'gulfOman'], ['gulfOman', 'gulfOmanN'], ['gulfOmanN', 'hormuz'], ['hormuz', 'gulfEast'],
  ['gulfEast', 'dubaiOff'], ['arabianSea', 'lakshadweep'], ['socotraN', 'lakshadweep'],
  ['lakshadweep', 'indianOcean'], ['arabianSea', 'indianOcean'], ['indianOcean', 'leeuwin'],
  ['leeuwin', 'bight'], ['bight', 'tasmaniaS'], ['tasmaniaS', 'tasman'], ['tasman', 'northCape'],
  ['northCape', 'haurakiNorth'], ['haurakiNorth', 'hauraki'], ['tasman', 'coralSea'],
  ['coralSea', 'cairnsOff'], ['coralSea', 'northCape'], ['haurakiNorth', 'kermadec'],
  ['kermadec', 'southPacific'], ['southPacific', 'eastPacific'], ['eastPacific', 'panamaGulf'],
  ['panamaGulf', 'balboa'], ['balboa', 'gatun'], ['gatun', 'colon'], ['colon', 'caribbeanSW'],
  ['caribbeanSW', 'caribbean'], ['caribbean', 'anegada'], ['anegada', 'stBartsOff'],
  ['stBartsOff', 'antiguaOff'], ['anegada', 'puertoRicoN'], ['stBartsOff', 'leewardAtl'],
  ['antiguaOff', 'leewardAtl'], ['leewardAtl', 'atlantic'], ['puertoRicoN', 'caicosN'],
  ['caicosN', 'eleutheraN'], ['eleutheraN', 'nassauOff'], ['nassauOff', 'nwProvidence'],
  ['nwProvidence', 'bimini'], ['bimini', 'miamiOff'], ['bimini', 'palmBeach'], ['miamiOff', 'palmBeach'],
  ['palmBeach', 'floridaE'], ['floridaE', 'carolina'], ['carolina', 'hatteras'], ['eleutheraN', 'atlanticW'],
  ['atlanticW', 'puertoRicoN'], ['atlanticW', 'leewardAtl'], ['atlanticW', 'hatteras'],
  ['floridaE', 'eleutheraN'], ['cadiz', 'stVincent'], ['stVincent', 'madeiraN'], ['madeiraN', 'atlantic'],
  ['atlantic', 'atlanticW'], ['atlantic', 'leewardAtl'], ['stVincent', 'lisbon'], ['lisbon', 'finisterre'],
  ['finisterre', 'biscay'], ['biscay', 'ushant'], ['ushant', 'channel'], ['channel', 'channelE'],
  ['channelE', 'dover'], ['dover', 'northSea'], ['northSea', 'frisian'], ['frisian', 'helgoland'],
  ['madeiraN', 'hatteras'], ['madeiraN', 'atlanticW'], ['madeiraN', 'leewardAtl'],
];
